=== MadhanKumarasamy/PAGE-XML/legacy/RelatedWork/UIBK_GroundTruth/impactgt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" targetNamespace="http://www.uibk.ac.at/ulb/dea/schemas/impactgt.xsd"  
        xmlns="http://www.uibk.ac.at/ulb/dea/schemas/impactgt.xsd"  xmlns:IGT="http://www.uibk.ac.at/ulb/dea/schemas/impactgt.xsd"  
        elementFormDefault="qualified" attributeFormDefault="unqualified">
     
    <xs:annotation>
        <xs:documentation xml:lang="en">Schema for representing Impact Ground Truth. Used as a guideline for service provider.</xs:documentation>
    </xs:annotation> 
    
    <!-- root element -->
    <xs:element name="Impact" type="ImpactGTType" />
    
    
    <!-- ImpactGT Type -->
    <xs:complexType name="ImpactGTType">
        <xs:annotation>
            <xs:documentation>The root element</xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="1">
            
            <xs:element name="Identifier" maxOccurs="unbounded" minOccurs="1" type="DescriptionType"/>
            <xs:element name="Layout" maxOccurs="1" minOccurs="1" type="LayoutType"/>
            </xs:sequence>
           <!--    <xs:element name="Filename" maxOccurs="1" minOccurs="1" type="xs:string"/>
            
              
             
           -->
    </xs:complexType>
    
    <xs:complexType name="DescriptionType">
        <xs:sequence maxOccurs="1">  
            <xs:element name="Type" type="xs:string" minOccurs="0"/>
            <xs:element name="Id" type="xs:string" minOccurs="0"/> 
        </xs:sequence>
  
    </xs:complexType>
    
    <xs:complexType name="LayoutType">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="Page"  maxOccurs="unbounded" type="PageType"/> 
        </xs:sequence>     
    </xs:complexType>
    
    
    
    <!-- PAGE TYPE -->
    <xs:complexType name="PageType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="BlockGroup"/>
        </xs:sequence> 
    </xs:complexType>
      
    <!-- GROUP OF BLOCKS -->   
    <xs:group name="BlockGroup">
        <xs:annotation>
            <xs:documentation>Group of available block types. These types are : Text, Illustration, Table and Unknown</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="TextBlock" type="TextBlockType">
                <xs:annotation>
                    <xs:documentation>A block of text.</xs:documentation>
                </xs:annotation>
            </xs:element>
            
              <xs:element name="IllustrationBlock" type="SimpleBlockType">
                <xs:annotation>
                    <xs:documentation>A picture or image.</xs:documentation>
                </xs:annotation>
            </xs:element>
              
            <xs:element name="TableBlock" type="TableBlockType">
                <xs:annotation>
                    <xs:documentation>A block in tableform.</xs:documentation>
                </xs:annotation>
            </xs:element>
                  
            <xs:element name="UnknownBlock" type="SimpleBlockType">
                <xs:annotation>
                    <xs:documentation>A block which can not be identified</xs:documentation>
                </xs:annotation>
                </xs:element> 
        </xs:choice>
    </xs:group>
    
      
    <!-- BLOCK TYPE (Plain Block) -->  
    <xs:complexType name="BlockType" >
        <xs:annotation>
            <xs:documentation>Base type for any kind of block on the page.</xs:documentation>
        </xs:annotation>
        <xs:attribute name="number" type="xs:integer" use="required"/>
        <xs:attribute name="x" type="xs:integer" use="required"/>
        <xs:attribute name="y" type="xs:integer" use="required"/>
        <xs:attribute name="w" type="xs:integer" use="required"/>
        <xs:attribute name="h" type="xs:integer" use="required"/>
        <xs:attribute name="orientation" default="horizontal" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="vertical"/>
                    <xs:enumeration value="horizontal"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
       
    </xs:complexType>
    
 
 
   <!--  TEXT BLOCK EXTENDS BLOCK -->
    <xs:complexType name="TextBlockType">
        <xs:annotation>
            <xs:documentation>A block of text.</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BlockType">       
                    <xs:annotation>
                        <xs:documentation>A textblock within a page</xs:documentation>
                    </xs:annotation>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:group ref="LogicalElementsGroup"/>
                    </xs:sequence> 
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <!--  TEXT BLOCK EXTENDS BLOCK -->
    <xs:complexType name="SimpleBlockType">
        <xs:annotation>
            <xs:documentation>A simple Blocktype with a textnode</xs:documentation>
        </xs:annotation>
        <xs:complexContent mixed="true">
            <xs:extension base="BlockType">       
                <xs:annotation>
                    <xs:documentation>A textblock within a page</xs:documentation>
                </xs:annotation>           
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!--  TABLE BLOCK EXTENDS BLOCK -->
    <xs:complexType name="TableBlockType">
        <xs:annotation>
            <xs:documentation>A block of text.</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="BlockType">       
                <xs:annotation>
                    <xs:documentation>A table within a page consisting of some cells</xs:documentation>
                </xs:annotation>
                <xs:sequence>
                    <xs:element name="Cell" minOccurs="1" maxOccurs="unbounded" type="xs:anyType"/>
                </xs:sequence> 
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <!--  GROUP OF LOGICAL ELEMENTS -->
    <xs:group name="LogicalElementsGroup">
        <xs:annotation>
            <xs:documentation>Group of available logical elements</xs:documentation>
        </xs:annotation>
        <xs:choice >
            <xs:element name="Paragraph" type="LogicalElementType">
                <xs:annotation>
                    <xs:documentation>A text paragraph</xs:documentation>
                </xs:annotation>
            </xs:element>
            
            <xs:element name="Pagenumber" type="LogicalElementType">
                <xs:annotation>
                    <xs:documentation>The pagenumber</xs:documentation>
                </xs:annotation>
            </xs:element>
            
            <xs:element name="Running_Title" type="LogicalElementType">
                <xs:annotation>
                    <xs:documentation>the running title on top of the page.</xs:documentation>
                </xs:annotation>
            </xs:element>
            
            <xs:element name="Headline" type="LogicalElementType">
                <xs:annotation>
                    <xs:documentation>A headline.</xs:documentation>
                </xs:annotation>
            </xs:element>
            
            <xs:element name="Marginalia" type="LogicalElementType">
                <xs:annotation>
                    <xs:documentation>A marginalia</xs:documentation>
                </xs:annotation>
            </xs:element>
            
            <xs:element name="Footnote" type="LogicalElementType">
                <xs:annotation>
                    <xs:documentation>A footnote.</xs:documentation>
                </xs:annotation>
            </xs:element>
            
            <xs:element name="UnknownElement" type="LogicalElementType">
                <xs:annotation>
                    <xs:documentation>None of the other logical elements</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:group>
    
    <!-- LOGICAL ELEMENT TYPE -->
    <xs:complexType name="LogicalElementType">
        <xs:annotation>
            <xs:documentation>Base type for any kind of block on the page.</xs:documentation>
        </xs:annotation>
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="TextStyle" type="TextStyleType"/>
          </xs:sequence>   
    </xs:complexType>
       
    <!-- TEXT STYLE TYPE -->   
    <xs:complexType name="TextStyleType">
        <xs:annotation> 
            <xs:documentation>Different kind of Textstyles</xs:documentation>
        </xs:annotation>
        
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="italic" default="false" use="optional" type="xs:boolean"/>
                <xs:attribute name="bold" default="false" use="optional" type="xs:boolean"/>
                <xs:attribute name="superscript" default="false" use="optional" type="xs:boolean"/>
                <xs:attribute name="unknown" default="false" use="optional" type="xs:boolean"/> 
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
 
    
</xs:schema>

=== MadhanKumarasamy/PAGE-XML/legacy/RelatedWork/UIBK_GroundTruth/0003.xml
<?xml version="1.0" encoding="UTF-8"?>
<IGT:Impact xmlns:IGT="http://www.uibk.ac.at/ulb/dea/schemas/impactgt.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uibk.ac.at/ulb/dea/schemas/impactgt.xsd http://www.uibk.ac.at/ulb/dea/schemas/impactgt.xsd">
<IGT:Identifier>
<IGT:Type>filename</IGT:Type>
<IGT:Id>dpo_35_0003</IGT:Id>
</IGT:Identifier>
<IGT:Layout>
<IGT:Page>
<IGT:TextBlock number="1" x="412" y="217" h="97" w="1072">
<IGT:Headline>
<IGT:TextStyle bold="true">KORT BEGRIP</IGT:TextStyle>
</IGT:Headline>
</IGT:TextBlock>
<IGT:TextBlock number="2" x="805" y="422" h="85" w="292">
<IGT:Headline>
<IGT:TextStyle bold="true">DER</IGT:TextStyle>
</IGT:Headline>
</IGT:TextBlock>
<IGT:TextBlock number="3" x="347" y="617" h="102" w="1220">
<IGT:Headline>
<IGT:TextStyle bold="true">WAERELD-HISTORIE</IGT:TextStyle>
</IGT:Headline>
</IGT:TextBlock>
<IGT:TextBlock number="4" x="485" y="832" h="87" w="915">
<IGT:Headline>
<IGT:TextStyle bold="true">VOOR DE JEUGD,</IGT:TextStyle>
</IGT:Headline>
</IGT:TextBlock>
<IGT:TextBlock number="5" x="805" y="1020" h="92" w="290">
<IGT:Headline>
<IGT:TextStyle bold="true">DOOR</IGT:TextStyle>
</IGT:Headline>
</IGT:TextBlock>
<IGT:TextBlock number="6" x="487" y="1205" h="107" w="927">
<IGT:Headline>
<IGT:TextStyle bold="true">J. F. MARTINET,</IGT:TextStyle>
</IGT:Headline>
</IGT:TextBlock>
<IGT:TextBlock number="7" x="555" y="1390" h="80" w="797">
<IGT:Headline>
<IGT:TextStyle bold="true">PREDIKANT TE ZUTPHEN, &amp;c.</IGT:TextStyle>
</IGT:Headline>
</IGT:TextBlock>
<IGT:TextBlock number="8" x="592" y="1570" h="72" w="675">
<IGT:Headline>
<IGT:TextStyle bold="true">MET KAARTEN.</IGT:TextStyle>
</IGT:Headline>
</IGT:TextBlock>
<IGT:TextBlock number="9" x="525" y="2122" h="72" w="850">
<IGT:Headline>
<IGT:TextStyle bold="true">TE AMSTERDAM, B IJ</IGT:TextStyle>
</IGT:Headline>
</IGT:TextBlock>
<IGT:TextBlock number="10" x="412" y="2200" h="90" w="1055">
<IGT:Headline>
<IGT:TextStyle bold="true">JOHANNES ALLART.</IGT:TextStyle>
</IGT:Headline>
</IGT:TextBlock>
<IGT:TextBlock number="11" x="682" y="2310" h="77" w="510">
<IGT:Headline>
<IGT:TextStyle bold="true">MDCCLXXXIX.</IGT:TextStyle>
</IGT:Headline>
</IGT:TextBlock>
</IGT:Page>
</IGT:Layout>
</IGT:Impact>

=== MadhanKumarasamy/PAGE-XML/legacy/RelatedWork/UIBK_GroundTruth/0005.xml
<?xml version="1.0" encoding="UTF-8"?>
<IGT:Impact xmlns:IGT="http://www.uibk.ac.at/ulb/dea/schemas/impactgt.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uibk.ac.at/ulb/dea/schemas/impactgt.xsd http://www.uibk.ac.at/ulb/dea/schemas/impactgt.xsd">
<IGT:Identifier>
<IGT:Type>filename</IGT:Type>
<IGT:Id>dpo_35_0005</IGT:Id>
</IGT:Identifier>
<IGT:Layout>
<IGT:Page>
<IGT:TextBlock number="1" x="757" y="230" h="77" w="350">
<IGT:Headline>
<IGT:TextStyle bold="true">AAN</IGT:TextStyle>
</IGT:Headline></IGT:TextBlock>
<IGT:TextBlock number="2" x="230" y="415" h="445" w="1385">
<IGT:Headline>
<IGT:TextStyle bold="true">ANTON REINHARD,
EGBERTA ANGELIQUE,</IGT:TextStyle>
</IGT:Headline></IGT:TextBlock>
<IGT:TextBlock number="3" x="827" y="942" h="170" w="257">
<IGT:Headline>
<IGT:TextStyle bold="true">EN</IGT:TextStyle>
</IGT:Headline></IGT:TextBlock>
<IGT:TextBlock number="4" x="330" y="1172" h="162" w="1260">
<IGT:Headline>
<IGT:TextStyle bold="true">AMELIA KAROLINA FALCK.</IGT:TextStyle>
</IGT:Headline></IGT:TextBlock>
<IGT:TextBlock number="5" x="272" y="1410" h="822" w="1322">
<IGT:Paragraph>
<IGT:TextStyle>Wie helpt niet gaarne Kinders, van eenen aan-
valligen aart, van zoete en zagte zeden, van eene
bekoorende leergierigheid, op de baan dier Weeten-
schappen, welken voor hun, by het toeneemen der
jaaren van geen gering belang zullen weezen? Ik
kom tot U met dit kleen geschenk, het eerste,
dat ik tot U dat einde kan aanbieden. Het ge-</IGT:TextStyle>
</IGT:Paragraph></IGT:TextBlock>
<IGT:TextBlock number="6" x="1377" y="2240" h="97" w="237">
<IGT:Paragraph>
<IGT:TextStyle>lei-</IGT:TextStyle>
</IGT:Paragraph>
</IGT:TextBlock>
</IGT:Page>
</IGT:Layout>
</IGT:Impact>
